Application/Cibercentro.WebApp/Controllers/TipoIngresoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cibercentro.Helpers;
using Cibercentro.Entidades;
using Cibercentro.Repositorio;
using Newtonsoft.Json;
using Cibercentro.WebApp.Common;

namespace Cibercentro.WebApp.Controllers
{
    public class TipoIngresoController : Controller
    {
        private readonly TipoIngresoRepositorio tipoIngresoRepositorio = new TipoIngresoRepositorio();

        [FiltroSeguridad]
        public ActionResult Index()
        {
            return View();
        }

        [FiltroSeguridad]
        public ActionResult Editar(int id = 0)
        {
            try
            {
                TipoIngreso model = null;
                if (id > 0)
                {
                    ViewData["Title"] = "Editar Tipo de Ingreso";
                    model = tipoIngresoRepositorio.GetOne(id);
                }
                else
                {
                    ViewData["Title"] = "Nuevo Tipo de Ingreso";
                    model = new TipoIngreso() { Estado = EstadoTipoIngreso.Habilitado };
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public ActionResult Editar(TipoIngreso model)
        {
            try
            {
                ValidEntity(model);
                if (ModelState.IsValid)
                {
                    bool agregar = model.TipoIngresoId == 0;
                    tipoIngresoRepositorio.Save(model);
                    return Json(new { mensaje = (agregar ? "El tipo de ingreso fue registrado." : "El tipo de ingreso fue editado."), id = model.TipoIngresoId });
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Error");
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        public ActionResult GetAllLikePagin(TipoIngreso filter, int pageSize, int pageIndex)
        {
            try
            {
                int totalRows = 0;
                List<TipoIngreso> lista = tipoIngresoRepositorio.GetAllLikePagin(filter, pageSize, pageIndex, ref totalRows);
                return Content(JsonConvert.SerializeObject(new
                {
                    lista = lista.Select(x => new
                    {
                        x.TipoIngresoId,
                        x.Nombre,
                        Estado = x.Estado.ToString()
                    }),
                    totalRows
                }));
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        #region Metodos

        private void ValidEntity(TipoIngreso item)
        {
            ModelState.Clear();
            if (string.IsNullOrEmpty(item.Nombre) || string.IsNullOrWhiteSpace(item.Nombre)) ModelState.AddModelError("Nombre", "Ingrese un nombre.");
        }

        #endregion
    }
}

Application/Cibercentro.WebApp/Views/TipoIngreso/Editar.cshtml
@model Cibercentro.Entidades.TipoIngreso

<link href="~/Content/pluggins/sweetalert/css/sweetalert.css" rel="stylesheet" />
<div class="row">
    @using (Html.BeginForm("Editar", "TipoIngreso", FormMethod.Post, new { @id = "form-editar", @class = "col-md-12" }))
    {
        <h3>@ViewData["Title"]</h3>
        <hr />

        <div class="form-row">
            <div class="col-sm-12 col-md-12 text-right">
                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-save"></i> Grabar</button>
                <a href="/TipoIngreso/Index" class="btn btn-sm btn-secondary"><i class="fa fa-chevron-left"></i> Regresar</a>
            </div>
        </div>
        <hr />
        <div id="mensaje"></div>
        @Html.HiddenFor(m => m.TipoIngresoId)
        <div class="form-group row">
            <label for="Nombre" class="col-sm-2 col-md-2 col-form-label">Nombre: </label>
            <div class="col-sm-10 col-md-10">
                @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control form-control-sm" })
            </div>
        </div>
        <div class="form-group row">
            <label for="Estado" class="col-sm-2 col-md-2 col-form-label">Estado: </label>
            <div class="col-sm-10 col-md-10">
                @Html.DropDownListFor(m => m.Estado, new SelectList(Cibercentro.Helpers.EnumHelper.ToList<Cibercentro.Entidades.EstadoTipoIngreso>(), "Value", "Name"), new { @class = "form-control form-control-sm" })
            </div>
        </div>
    }
</div>
<script src="~/Content/pluggins/sweetalert/js/sweetalert.min.js"></script>
<script>
    $(function () {
        $("#form-editar").submit(function (e) {
            swal({
                title: "Estas seguro?", text: "Los datos seran grabados", type: "warning",
                confirmButtonColor: "#f2b701", confirmButtonText: "Si", cancelButtonText: "No",
                showCancelButton: true, closeOnConfirm: false, showLoaderOnConfirm: true
            }, function (isConfirm) {
                if (isConfirm) {
                    var model = $("#form-editar").serialize();
                    $.ajax({
                        type: "POST",
                        url: "/TipoIngreso/Editar",
                        data: model,
                        dataType: 'json',
                        beforeSend: function () {
                            $('#form-editar button').attr("disabled", "disabled");
                            $("#mensaje").hide();
                            helper.wait.append('#mensaje');
                        },
                        complete: function () {
                            $('#form-modal-editar button').removeAttr("disabled");
                            helper.wait.remove('#mensaje');
                        },
                        success: function (result) {
                            swal({ title: "Alerta!", text: result.mensaje, type: "success" }, function () {
                                location.href = "/TipoIngreso/Index";
                            });
                        },
                        error: function (result) {
                            swal.close();
                            helper.wait.remove('#mensaje');
                            helper.error.show('#mensaje', result.responseText);
                            $('#form-editar button').removeAttr("disabled");
                        }
                    });
                }
            });
            e.preventDefault();
        });

    });
</script>

Application/Cibercentro.WebApp/Views/TipoIngreso/Index.cshtml
@{
    ViewData["Title"] = "Tipo Ingreso";
}
<div class="row">
    <div class="col-md-12">
        <h3>Tipos de ingreso</h3>
        <hr />
        <div class="form-row">
            <div class="col-sm-8 col-md-8">
                <input class="form-control form-control-sm" disabled="disabled" />
            </div>
            <div class="col-sm-2 col-md-2">
                <input class="form-control form-control-sm" disabled="disabled" />
            </div>
            <div class="col-sm-2 col-md-2 text-right">
                <button type="button" class="btn btn-sm btn-secondary"><i class="fa fa-search"></i> Buscar</button>
                <a href="/TipoIngreso/Editar" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Nuevo</a>
            </div>
        </div>
        <hr />
        <div class="table-responsive">
            <table id="tblIndex"
                   class="table table-bordered table-hover"
                   data-pagesize="@Cibercentro.WebApp.Common.SettingsManager.PageSize"
                   data-pageindex="1"
                   data-totalrows="0"
                   data-function="tipoingreso_index.Listar"
                   data-paginator="paginator">
                <thead>
                    <tr class="thead-dark">
                        <th width="20"></th>
                        <th width="20">Nº</th>
                        <th>Nombre</th>
                        <th width="150">Estado</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
        <div class="form-row">
            <div class="col-md-12 text-right" id="paginator"></div>
        </div>
    </div>
</div>
<script>

    var tipoingreso_index = {
        Listar: function (page) {
            var table = $("#tblIndex");
            var model = {
                'pageIndex': page,
                'pageSize': table.data('pagesize')
            };
            $.ajax({
                url: "/TipoIngreso/GetAllLikePagin",
                type: "GET",
                data: model,
                dataType: "json",
                success: function (data) {
                    table.data('pageindex', page);
                    table.data('totalrows', data.totalRows);
                    tipoingreso_index.GenerarTabla(table, data.lista);
                    if (data.totalRows === 0) table.children('tbody').append("<tr><td colspan='4' class='text-center text-bold'>No existen registros</td></td>");
                },
                error: function (data) {
                    helper.error.show('msgIndex', data.responseText);
                }
            });
        },
        GenerarTabla: function (table, lista) {
            var tbody = table.children('tbody');
            tbody.children('tr').remove();
            var rows = '';
            var numero = (table.data('pagesize') * table.data('pageindex')) - table.data('pagesize');
            $.each(lista, function (i, r) {
                rows += '<tr>';
                rows += '<td class="text-center">';
                rows += helper.string.format('<a href="/TipoIngreso/Editar/{0}" title="Editar"><i class="fa fa-pencil text-warning"></i></a>', r.TipoIngresoId);
                rows += '</td>';
                rows += helper.string.format('<td class="text-right">{0}</td>', ++numero);
                rows += helper.string.format('<td>{0}</td>', r.Nombre);
                rows += helper.string.format('<td class="text-center">{0}</td>', r.Estado);
                rows += '</tr>';
            });
            helper.pagination.update(table);
            tbody.append(rows);
        }
    };
    $(function () {
        $('#tblIndex input[type="text"]').keypress(function (e) {
            var key = e.keyCode || event.keyCode;
            if (key === 13) tipoingreso_index.Listar(1);
        });
        tipoingreso_index.Listar(1);
    });
</script>