Application/Cibercentro.WebApp/Controllers/DescuentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cibercentro.Helpers;
using Cibercentro.Entidades;
using Cibercentro.Repositorio;
using Cibercentro.WebApp.Common;
using Newtonsoft.Json;

namespace Cibercentro.WebApp.Controllers
{
    public class DescuentoController : Controller
    {
        private readonly DescuentoRepositorio descuentoRepositorio = new DescuentoRepositorio();

        [FiltroSeguridad]
        public ActionResult Index()
        {
            return View();
        }

        [FiltroSeguridad]
        public ActionResult Editar(int id = 0)
        {
            try
            {
                Descuento model = null;
                if (id > 0)
                {
                    ViewData["Title"] = "Editar Descuento";
                    model = descuentoRepositorio.GetOne(id);
                }
                else
                {
                    ViewData["Title"] = "Nuevo Descuento";
                    model = new Descuento() { Fecha = DateTime.Today, Estado = EstadoDescuento.Pendiente };
                }
                return View(model);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                throw ex;
            }
        }

        [FiltroSeguridad]
        [HttpPost]
        public ActionResult Editar(Descuento model)
        {
            try
            {
                ValidEntity(model);
                if (ModelState.IsValid)
                {
                    bool agregar = model.DescuentoId == 0;
                    int i = descuentoRepositorio.CountBy(x => x.Fecha == model.Fecha && x.EmpleadoId == model.EmpleadoId && x.DescuentoId != model.DescuentoId);
                    if (i > 0) throw new Exception("El encargado ingresado ya tiene un descuento en la misma fecha.");
                    else
                    {
                        if (agregar)
                        {
                            model.EmpleadoCreacionId = ((UserInformation)Session["user"]).UserId;
                            model.FechaCreacion = DateTime.Now;
                            model.Estado = EstadoDescuento.Pendiente;
                        }
                        else
                        {
                            Descuento descuento = descuentoRepositorio.GetOne(x => x.DescuentoId == model.DescuentoId);
                            descuento.EmpleadoId = model.EmpleadoId;
                            descuento.Fecha = model.Fecha;
                            descuento.Motivo = model.Motivo;
                            descuento.Cantidad = model.Cantidad;
                            descuento.FechaActualizacion = DateTime.Now;
                            descuento.EmpleadoActualizacionId = ((UserInformation)Session["user"]).UserId;
                            model = descuento;
                        }
                        descuentoRepositorio.Save(model);
                        return Json(new { mensaje = agregar ? "El descuento fue registrado." : "El descuento fue actualizado", id = model.DescuentoId });
                    }
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Error");
                }

            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        public ActionResult GetAllLikePagin(Descuento filter, int pageSize, int pageIndex)
        {
            try
            {
                int totalRows = 0;
                List<Descuento> lista = descuentoRepositorio.GetAllLikePagin(filter, pageIndex, pageSize, ref totalRows);
                return Content(JsonConvert.SerializeObject(new
                {
                    lista = lista.Select(x => new
                    {
                        x.DescuentoId,
                        x.EmpleadoNombreCompleto,
                        Cantidad = x.Cantidad.ToString("###########0.00"),
                        x.Motivo,
                        Fecha = x.Fecha.ToString("dd/MM/yyyy"),
                        Estado = x.Estado.ToString(),
                        Editar = x.Estado == EstadoDescuento.Pendiente
                    }),
                    totalRows
                }));
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        #region Metodos

        public void ValidEntity(Descuento item)
        {
            ModelState.Clear();
            if (item.EmpleadoId <= 0) ModelState.AddModelError("EmpleadoId", "Seleccion un encargado.");
            if (string.IsNullOrEmpty(item.Motivo) || string.IsNullOrWhiteSpace(item.Motivo)) ModelState.AddModelError("Motivo", "Ingrese un motivo.");
            if (item.Cantidad <= 0) ModelState.AddModelError("Cantidad", "La cantidad debe ser mayor a 0.");
            //if (item.Estado <= 0) ModelState.AddModelError("Estado", "Seleccione un estado.");
        }

        #endregion

    }
}

Application/Cibercentro.WebApp/Views/Descuento/Editar.cshtml
@model Cibercentro.Entidades.Descuento
<link href="~/Content/pluggins/sweetalert/css/sweetalert.css" rel="stylesheet" />
<link href="~/Content/pluggins/select2/css/select2.min.css" rel="stylesheet" />
<link href="~/Content/pluggins/select2/css/select2.bootstrap4.css" rel="stylesheet" />
<link href="~/Content/pluggins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />

<div class="row">

    @using (Html.BeginForm("Editar", "Descuento", FormMethod.Post, new { @id = "form-editar", @class = "col-md-12" }))
    {
        <h2>@ViewBag.Title</h2>
        <hr />
        <div class="form-row">
            <div class="col-sm-12 col-md-12 text-right">
                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-save"></i> Grabar</button>
                <a href="/Descuento/Index" class="btn btn-sm btn-secondary"><i class="fa fa-chevron-left"></i> Regresar</a>
            </div>
        </div>
        <hr />
        <div id="mensaje"></div>
        @Html.HiddenFor(m => m.DescuentoId)
        <div class="form-group row">
            <label for="EmpleadoId" class="col-sm-2 col-md-2 col-form-label text-truncate">Encargado: </label>
            <div class="col-sm-5 col-md-5">
                <select id="EmpleadoId" name="EmpleadoId" class="form-control form-control-sm">
                    @if (Model.EmpleadoId > 0)
                    {
                        <option value="@Model.EmpleadoId" selected>@(Model.EmpleadoNombreCompleto)</option>
                    }
                </select>
            </div>
            <label for="FechaRegistro" class="col-sm-2 col-md-2 col-form-label text-truncate">Fecha: </label>
            <div class="col-sm-3 col-md-3">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-calendar"></i></span>
                    </div>
                    @Html.TextBoxFor(m => m.Fecha, Model.Fecha.ToString("dd/MM/yyyy"), new { @class = "form-control form-control-sm datepicker", @autocomplete = "off" })
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="Motivo" class="col-sm-2 col-md-2 col-form-label text-truncate">Motivo</label>
            <div class="col-sm-10 col-md-10">
                @Html.TextBoxFor(m => m.Motivo, new { @class = "form-control form-control-sm" })
            </div>
        </div>
        <div class="form-group row">
            <label for="Cantidad" class="col-sm-2 col-md-2 col-form-label text-truncate">Cantidad</label>
            <div class="col-sm-4 col-md-4">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">S/</span>
                    </div>
                    @Html.TextBoxFor(m => m.Cantidad, new { @class = "form-control form-control-sm text-right", @step = "0.01", @type = "number" })
                </div>
            </div>

            @*<label for="Estado" class="col-sm-2 col-md-2 col-form-label">Estado: </label>
            <div class="col-sm-4 col-md-4">
                @Html.DropDownListFor(m => m.Estado, new SelectList(Cibercentro.Helpers.EnumHelper.ToList<Cibercentro.Entidades.EstadoDescuento>(), "Value", "Name"), new { @class = "form-control form-control-sm" })
            </div>*@
        </div>
    }

</div>

<script src="~/Content/pluggins/sweetalert/js/sweetalert.min.js"></script>
<script src="~/Content/pluggins/select2/js/select2.min.js"></script>
<script src="~/Content/pluggins/select2/js/i18n/es.js"></script>
<script src="~/Content/pluggins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="~/Content/pluggins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>
<script>
    $(function () {
        $('.datepicker').datepicker({
            language: 'es',
            orientation: 'bottom',
            'autoclose': true,
            format: 'dd/mm/yyyy'
        });
        $("#EmpleadoId").select2({
            language: "es",
            ajax: {
                url: '/Empleado/GetFirst',
                dataType: 'json',
                delay: 150,
                data: function (params) {
                    return { 'filter.Nombre': params.term, 'filter.Apellido': params.term };
                },
                processResults: function (data) {
                    var lista = [];
                    data.lista.forEach(function (x) { lista.push({ id: x.EmpleadoId, text: x.NombreCompleto }); });
                    return { results: lista };
                }
            },
            minimumInputLength: 2
        });
        $('#form-editar').submit(function (e) {
            swal({
                title: "Estas seguro?", text: "Los datos seran grabados", type: "warning",
                confirmButtonColor: "#f2b701", confirmButtonText: "Si", cancelButtonText: "No",
                showCancelButton: true, closeOnConfirm: false, showLoaderOnConfirm: true
            }, function (isConfirm) {
                if (isConfirm) {
                    var model = $("#form-editar").serialize();
                    $.ajax({
                        type: "POST",
                        url: "/Descuento/Editar",
                        data: model,
                        dataType: 'json',
                        beforeSend: function () {
                            $('#form-editar button').attr("disabled", "disabled");
                            $("#mensaje").hide();
                            helper.wait.append('#mensaje');
                        },
                        complete: function () {
                            $('#form-modal-editar button').removeAttr("disabled");
                            helper.wait.remove('#mensaje');
                        },
                        success: function (result) {
                            swal({ title: "Alerta!", text: result.mensaje, type: "success" }, function () {
                                location.href = "/Descuento/Index";
                                //location.href = "/Seguridad/Usuario/Editar/" + result.id;
                            });
                        },
                        error: function (result) {
                            swal.close();
                            helper.wait.remove('#mensaje');
                            helper.error.show('#mensaje', result.responseText);
                            $('#form-editar button').removeAttr("disabled");
                        }
                    });
                }
            });
            e.preventDefault();
        });
    });
</script>

Application/Cibercentro.WebApp/Views/Descuento/Index.cshtml
@{
    ViewBag.Title = "Descuentos";
}

<div class="row">
    <div class="col-md-12">
        <h3>Lista de descuentos</h3>
        <hr />
        <div class="form-row">
            <div class="col-sm-8 col-md-8">
                <input class="form-control form-control-sm" disabled="disabled" />
            </div>
            <div class="col-sm-2 col-md-2">
                <input class="form-control form-control-sm" disabled="disabled" />
            </div>
            <div class="col-sm-2 col-md-2 text-right">
                <button type="button" class="btn btn-sm btn-secondary"><i class="fa fa-search"></i> Buscar</button>
                <a href="/Descuento/Editar" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Nuevo</a>
            </div>
        </div>
        <hr />
        <div class="table-responsive">
            <table id="tblIndex"
                   class="table table-bordered table-hover"
                   data-pagesize="@Cibercentro.WebApp.Common.SettingsManager.PageSize"
                   data-pageindex="1"
                   data-totalrows="0"
                   data-function="descuento_index.Listar"
                   data-paginator="paginator">
                <thead>
                    <tr class="thead-dark">
                        <th width="20"></th>
                        <th width="20">Nº</th>
                        <th>Empleado</th>
                        <th width="300">Motivo</th>
                        <th width="200">Fecha</th>
                        <th width="150">Cantidad</th>
                        <th width="150">Estado</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
        <div class="form-row">
            <div class="col-md-12 text-right" id="paginator"></div>
        </div>
    </div>
</div>
<script>

    var descuento_index = {
        Listar: function (page) {
            var table = $("#tblIndex");
            var model = {
                'pageIndex': page,
                'pageSize': table.data('pagesize')
            };
            $.ajax({
                url: "/Descuento/GetAllLikePagin",
                type: "GET",
                data: model,
                dataType: "json",
                success: function (data) {
                    table.data('pageindex', page);
                    table.data('totalrows', data.totalRows);
                    descuento_index.GenerarTabla(table, data.lista);
                    if (data.totalRows === 0) table.children('tbody').append("<tr><td colspan='7' class='text-center text-bold'>No existen registros</td></td>");
                },
                error: function (data) {
                    helper.error.show('msgIndex', data.responseText);
                }
            });
        },
        GenerarTabla: function (table, lista) {
            var tbody = table.children('tbody');
            tbody.children('tr').remove();
            var rows = '';
            var numero = (table.data('pagesize') * table.data('pageindex')) - table.data('pagesize');
            $.each(lista, function (i, r) {
                rows += '<tr>';
                rows += '<td class="text-center">';
                rows += helper.string.format('<a href="/Descuento/Editar/{0}" title="Editar"><i class="fa fa-pencil text-warning"></i></a>', r.DescuentoId);
                rows += '</td>';
                rows += helper.string.format('<td class="text-right">{0}</td>', ++numero);
                rows += $('<td>', { text: r.EmpleadoNombreCompleto }).prop('outerHTML');
                rows += $('<td>', { text: r.Motivo }).prop('outerHTML');
                rows += $('<td>', { text: r.Fecha, class: "text-center" }).prop('outerHTML');
                rows += $('<td>', { text: r.Cantidad, class: "text-right" }).prop('outerHTML');
                rows += $('<td>', { text: r.Estado, class: "text-center" }).prop('outerHTML');
                rows += '</tr>';
            });
            helper.pagination.update(table);
            tbody.append(rows);
        }
    };
    $(function () {
        $('#tblIndex input[type="text"]').keypress(function (e) {
            var key = e.keyCode || event.keyCode;
            if (key === 13) descuento_index.Listar(1);
        });
        descuento_index.Listar(1);
    });
</script>