Application/Cibercentro.WebApp/Controllers/IngresoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cibercentro.Helpers;
using Cibercentro.Entidades;
using Cibercentro.Repositorio;
using Newtonsoft.Json;
using Cibercentro.WebApp.Common;
using Cibercentro.Entidades.Filtro;

namespace Cibercentro.WebApp.Controllers
{
    public class IngresoController : Controller
    {
        private readonly IngresoRepositorio ingresoRepositorio = new IngresoRepositorio();
        private readonly TipoIngresoRepositorio tipoIngresoRepositorio = new TipoIngresoRepositorio();
        private readonly OrdenVentaRepositorio ordenVentaRepositorio = new OrdenVentaRepositorio();

        [FiltroSeguridad]
        public ActionResult Index()
        {
            return View();
        }

        [FiltroSeguridad]
        public ActionResult Editar(int id = 0)
        {
            try
            {
                UserInformation user = (UserInformation)Session["user"];
                Ingreso model = null;
                if (id > 0)
                {
                    ViewData["Title"] = "Editar Ingreso";
                    model = ingresoRepositorio.GetOne(id);
                }
                else
                {
                    ViewData["Title"] = "Nuevo Ingreso";
                    var tiposIngreso = tipoIngresoRepositorio.GetAllBy(x => x.Estado == EstadoTipoIngreso.Habilitado);
                    model = new Ingreso()
                    {
                        EmpleadoId = user.UserId,
                        EmpleadoNombreCompleto = user.Name,
                        FechaRegistro = DateTime.Now,
                        Detalles = tiposIngreso.Select(x => new IngresoDetalle { TipoIngresoId = x.TipoIngresoId, TipoIngreso = x }).ToList()
                    };
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [FiltroSeguridad, HttpPost]
        public ActionResult Editar(Ingreso model)
        {
            try
            {
                ValidEntity(model);
                if (ModelState.IsValid)
                {
                    UserInformation user = (UserInformation)Session["user"];

                    bool agregar = model.IngresoId == 0;
                    if (agregar)
                    {
                        var i = ingresoRepositorio.CountBy(x => x.EmpleadoId == model.EmpleadoId && x.FechaRegistro == model.FechaRegistro);
                        if (i > 0) throw new Exception("Ya existe un registro ingresado a ese usuario y a esa misma fecha.");
                        model.FechaCreacion = DateTime.Now;
                        model.EmpleadoCreacionId = user.UserId;
                        model.Cantidad = model.Detalles != null ? model.Detalles.Sum(x => x.Cantidad) : 0;
                    }
                    else
                    {
                        Ingreso ingreso = ingresoRepositorio.GetOne(model.IngresoId);
                        if (ingreso == null) throw new Exception("El ingreso que trata de guardar no existe en la base de datos.");
                        ingreso.FechaActualizacion = DateTime.Now;
                        ingreso.EmpleadoActualizacionId = user.UserId;
                        ingreso.FechaRegistro = model.FechaRegistro;
                        ingreso.Cantidad = model.Cantidad;
                        ingreso.EmpleadoId = model.EmpleadoId;
                        ingreso.Observacion = model.Observacion;
                        ingreso.Cantidad = model.Detalles != null ? model.Detalles.Sum(x => x.Cantidad) : 0;
                        ingreso.Detalles = model.Detalles;
                        model = ingreso;
                    }
                    ingresoRepositorio.Save(model);
                    return Json(new { mensaje = (agregar ? "El ingreso fue registrado." : "El ingreso fue editado."), id = model.IngresoId });
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Error");
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }
        
        public ActionResult ValidarMontoTienda(Ingreso model)
        {
            try
            {
                ValidEntity(model);
                if (ModelState.IsValid)
                {
                    DateTime hoy = DateTime.Today;
                    UserInformation user = Session["user"] != null ? (UserInformation)Session["user"] : new UserInformation();
                    List<OrdenVenta> ordenVentas = ordenVentaRepositorio.GetAllBy(x => x.EmpleadoCreacionId == user.UserId && x.FechaCreacion.Year == hoy.Year && x.FechaCreacion.Month == hoy.Month && x.FechaCreacion.Day == hoy.Day);
                    IngresoDetalle ingresoDetalle = model.Detalles.SingleOrDefault(x => x.TipoIngresoId == SettingsManager.tipoIngresoTiendaId);
                    decimal cantidadTotal = ingresoDetalle != null ? ingresoDetalle.Cantidad : 0;

                    return Content(JsonConvert.SerializeObject(new
                    {
                        ok = cantidadTotal == ordenVentas.Sum(x => x.Total),
                        cantidadIngreso = cantidadTotal,
                        cantidadVenta = ordenVentas.Sum(x => x.Total)
                    }), "application/json");
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Error");
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        public ActionResult GetAllLikePagin(IngresoFiltro filter, int pageSize, int pageIndex)
        {
            try
            {
                int totalRows = 0;
                List<Ingreso> lista = ingresoRepositorio.GetAllLikePagin(filter, pageSize, pageIndex, ref totalRows);
                return Content(JsonConvert.SerializeObject(new
                {
                    lista = lista.Select(x => new
                    {
                        x.IngresoId,
                        x.EmpleadoNombreCompleto,
                        FechaRegistro = x.FechaRegistro.ToString("dd/MM/yyyy"),
                        Cantidad = x.Cantidad.ToString("###########0.00")
                    }),
                    totalRows
                }));
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        #region Metodos

        public void ValidEntity(Ingreso item)
        {
            ModelState.Clear();
            if (item.Detalles != null && item.Detalles.Sum(x => x.Cantidad) < 0) ModelState.AddModelError("Cantidad", "La cantidad del ingreso no puede ser menor a 0.");
            if (item.EmpleadoId <= 0) ModelState.AddModelError("EmpleadoId", "Debe seleccionar un personal.");
        }

        #endregion
    }
}

Application/Cibercentro.WebApp/Views/Ingreso/Editar.cshtml
@model Cibercentro.Entidades.Ingreso

<link href="~/Content/pluggins/sweetalert/css/sweetalert.css" rel="stylesheet" />
<link href="~/Content/pluggins/select2/css/select2.min.css" rel="stylesheet" />
<link href="~/Content/pluggins/select2/css/select2.bootstrap4.css" rel="stylesheet" />
<link href="~/Content/pluggins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />

<div class="row">
    @using (Html.BeginForm("Editar", "Ingreso", FormMethod.Post, new { @id = "form-editar", @class = "col-md-12" }))
    {
        <h3>@ViewData["Title"]</h3>
        <hr />

        <div class="form-row">
            <div class="col-sm-12 col-md-12 text-right">
                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-save"></i> Grabar</button>
                <a href="/Ingreso/Index" class="btn btn-sm btn-secondary"><i class="fa fa-chevron-left"></i> Regresar</a>
            </div>
        </div>
        <hr />
        <div id="mensaje"></div>
        @Html.HiddenFor(m => m.IngresoId)
        <div class="form-group row">
            <label for="EmpleadoId" class="col-sm-2 col-md-2 col-form-label text-truncate">Encargado: </label>
            <div class="col-sm-4 col-md-4">
                <select id="EmpleadoId" name="EmpleadoId" class="form-control form-control-sm">
                    @if (Model.EmpleadoId > 0)
                    {
                        <option value="@Model.EmpleadoId" selected>@Model.EmpleadoNombreCompleto</option>
                    }
                </select>
            </div>
            <label for="Fecha" class="col-sm-2 col-md-2 col-form-label text-truncate">Fecha: </label>
            <div class="col-sm-4 col-md-4">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-calendar"></i></span>
                    </div>
                    @Html.TextBoxFor(m => m.FechaRegistro, Model.FechaRegistro.ToString("dd/MM/yyyy"), new { @class = "form-control form-control-sm datepicker", @autocomplete = "off" })
                </div>
            </div>
        </div>
        if (Model.Detalles != null)
        {
            <hr />
            <table class="table table-bordered">
                <tbody>
                    @{
                        int i = 0;
                        foreach (var detalle in Model.Detalles)
                        {
                            <tr class="thead-dark">
                                <th width="400">
                                    <input type="hidden" name="Detalles[@i].IngresoId" value="@detalle.IngresoId" />
                                    <input type="hidden" name="Detalles[@i].TipoIngresoId" value="@detalle.TipoIngresoId" />
                                    @detalle.TipoIngreso.Nombre
                                </th>
                                <td>
                                    <div class="input-group input-group-sm">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">S/</span>
                                        </div>
                                        <input type="number" step="0.01" name="Detalles[@i].Cantidad" value="@detalle.Cantidad.ToString("###########0.00")" class="form-control form-control-sm text-right" />
                                    </div>
                                </td>
                            </tr>
                            i++;
                        }

                    }
                </tbody>
            </table>

            <hr />
        }
        <div class="form-group row">
            <label for="Observacion" class="col-sm-2 col-md-2 col-form-label text-truncate">Observacion: </label>
            <div class="col-sm-10 col-md-10">
                @Html.TextAreaFor(m => m.Observacion, new { @class = "form-control form-control-sm", @rows = "6" })
            </div>
        </div>
    }
</div>
<script src="~/Content/pluggins/sweetalert/js/sweetalert.min.js"></script>
<script src="~/Content/pluggins/select2/js/select2.min.js"></script>
<script src="~/Content/pluggins/select2/js/i18n/es.js"></script>
<script src="~/Content/pluggins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="~/Content/pluggins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>
<script>
    $(function () {
        $('.datepicker').datepicker({
            language: 'es',
            orientation: 'bottom',
            'autoclose': true,
            format: 'dd/mm/yyyy'
        });
        $("#form-editar").submit(function (e) {

            var model = $("#form-editar").serialize();
            $.get("/Ingreso/ValidarMontoTienda", model, function (data) {
                swal({
                    title: "Estas seguro?", text: data.ok ? "Se guardaran los datos" : "Guardara con unas incosistencias, la venta realizada hoy es: " + helper.format.decimal(data.cantidadVenta), type: "warning",
                    confirmButtonColor: "#f2b701", confirmButtonText: "Si", cancelButtonText: "No",
                    showCancelButton: true, closeOnConfirm: false, showLoaderOnConfirm: true
                }, function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            type: "POST",
                            url: "/Ingreso/Editar",
                            data: model,
                            dataType: 'json',
                            beforeSend: function () {
                                $('#form-editar button').attr("disabled", "disabled");
                                $("#mensaje").hide();
                                helper.wait.append('#mensaje');
                            },
                            complete: function () {
                                $('#form-modal-editar button').removeAttr("disabled");
                                helper.wait.remove('#mensaje');
                            },
                            success: function (result) {
                                swal({ title: "Alerta!", text: result.mensaje, type: "success" }, function () {
                                    location.href = "/Ingreso/Index";
                                });
                            },
                            error: function (result) {
                                swal.close();
                                helper.wait.remove('#mensaje');
                                helper.error.show('#mensaje', result.responseText);
                                $('#form-editar button').removeAttr("disabled");
                            }
                        });
                    }
                });
            });


            e.preventDefault();
        });
        $("#EmpleadoId").select2({
            language: "es",
            ajax: {
                url: '/Empleado/GetFirst',
                dataType: 'json',
                delay: 150,
                data: function (params) {
                    return { 'filter.Nombre': params.term, 'filter.Apellido': params.term };
                },
                processResults: function (data) {
                    var lista = [];
                    data.lista.forEach(function (x) { lista.push({ id: x.EmpleadoId, text: x.NombreCompleto }); });
                    return { results: lista };
                }
            },
            minimumInputLength: 2
        });
    });
</script>

Application/Cibercentro.WebApp/Views/Ingreso/Index.cshtml
@{
    ViewBag.Title = "Ingresos";
}
<link href="~/Content/pluggins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-12">
        <h3>Lista de ingresos</h3>
        <hr />
        <div class="form-row">
            <div class="col-sm-12 col-md-12 mb-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                    </div>
                    <input class="form-control form-control-sm" placeholder="Ingrese nombre del encargado" id="EmpleadoNombre" />
                </div>
            </div>
            <div class="col-sm-6 col-md-6 mb-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                    </div>
                    <input class="form-control form-control-sm datepicker" placeholder="Seleccione la fecha desde" id="FechaDesde" disabled="disabled" />
                </div>
            </div>
            <div class="col-sm-6 col-md-6 mb-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                    </div>
                    <input class="form-control form-control-sm datepicker" placeholder="Seleccione la fecha hasta (opcional)" id="FechaHasta" disabled="disabled" />
                </div>
            </div>
            <div class="col-sm-6 col-md-6 mb-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text">S/</span>
                    </div>
                    <input class="form-control form-control-sm" placeholder="Ingrese la cantidad desde" type="number" step="0.01" id="CantidadDesde" />
                </div>
            </div>
            <div class="col-sm-6 col-md-6 mb-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text">S/</span>
                    </div>
                    <input class="form-control form-control-sm" placeholder="Ingrese la cantidad hasta (opcional)" type="number" step="0.01" id="CantidadHasta" />
                </div>
            </div>
            <div class="col-sm-12 col-md-12 text-right">
                <button id="btnBuscar" type="button" class="btn btn-sm btn-secondary"><i class="fa fa-search"></i> Buscar</button>
                <a href="/Ingreso/Editar" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Nuevo</a>
            </div>
        </div>

        <hr />
        <div class="table-responsive">
            <table id="tblIndex"
                   class="table table-bordered table-hover"
                   data-pagesize="@Cibercentro.WebApp.Common.SettingsManager.PageSize"
                   data-pageindex="1"
                   data-totalrows="0"
                   data-function="ingreso_index.Listar"
                   data-paginator="paginator">
                <thead>
                    <tr class="thead-dark">
                        <th width="20"></th>
                        <th width="20">Nº</th>
                        <th>Encargado</th>
                        <th width="150">Fecha</th>
                        <th width="150">Cantidad</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
        <div class="form-row">
            <div class="col-md-12 text-right" id="paginator"></div>
        </div>
    </div>
</div>
<script src="~/Content/pluggins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="~/Content/pluggins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>
<script>

    var ingreso_index = {
        Listar: function (page) {
            var desde = new Date(document.getElementById('FechaDesde').value.replace(/(\d{2})-(\d{2})-(\d{4})/, "$2/$1/$3"));
            var table = $("#tblIndex");
            var model = {
                'filter.EmpleadoNombre': document.getElementById('EmpleadoNombre').value,
                'filter.FechaDesde': document.getElementById('FechaDesde').value,
                'filter.FechaHasta': document.getElementById('FechaHasta').value,
                'filter.CantidadDesde': document.getElementById('CantidadDesde').value,
                'filter.CantidadHasta': document.getElementById('CantidadHasta').value,
                'pageIndex': page,
                'pageSize': table.data('pagesize')
            };
            $.ajax({
                url: "/Ingreso/GetAllLikePagin",
                type: "GET",
                data: model,
                dataType: "json",
                success: function (data) {
                    table.data('pageindex', page);
                    table.data('totalrows', data.totalRows);
                    ingreso_index.GenerarTabla(table, data.lista);
                    if (data.totalRows === 0) table.children('tbody').append("<tr><td colspan='5' class='text-center text-bold'>No existen registros</td></td>");
                },
                error: function (data) {
                    helper.error.show('msgIndex', data.responseText);
                }
            });
        },
        GenerarTabla: function (table, lista) {
            var tbody = table.children('tbody');
            tbody.children('tr').remove();
            var rows = '';
            var numero = (table.data('pagesize') * table.data('pageindex')) - table.data('pagesize');
            $.each(lista, function (i, r) {
                rows += '<tr>';
                rows += '<td class="text-center">';
                rows += helper.string.format('<a href="/Ingreso/Editar/{0}" title="Editar"><i class="fa fa-pencil text-warning"></i></a>', r.IngresoId);
                rows += '</td>';
                rows += helper.string.format('<td class="text-right">{0}</td>', ++numero);
                rows += $('<td>', { text: r.EmpleadoNombreCompleto }).prop('outerHTML');
                rows += $('<td>', { text: r.FechaRegistro, class: "text-center" }).prop('outerHTML');
                rows += $('<td>', { text: r.Cantidad, class: "text-right" }).prop('outerHTML');
                rows += '</tr>';
            });
            helper.pagination.update(table);
            tbody.append(rows);
        }
    };
    $(function () {
        $('.datepicker').datepicker({
            language: 'es',
            orientation: 'bottom',
            'autoclose': true,
            format: 'dd/mm/yyyy'
        });
        document.getElementById('btnBuscar').onclick = function (e) {
            ingreso_index.Listar(1);
        }

        ingreso_index.Listar(1);
    });
</script>