Application/Cibercentro.WebApp/Controllers/OrdenVentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cibercentro.Helpers;
using Cibercentro.Entidades;
using Cibercentro.Repositorio;
using Newtonsoft.Json;
using Cibercentro.WebApp.Common;
using Cibercentro.Entidades.Filtro;

namespace Cibercentro.WebApp.Controllers
{
    public class OrdenVentaController : Controller
    {
        private readonly OrdenVentaRepositorio ordenVentaRepositorio = new OrdenVentaRepositorio();

        [FiltroSeguridad]
        public ActionResult Index()
        {
            return View();
        }

        [FiltroSeguridad]
        public ActionResult Editar(string id = null)
        {
            try
            {
                OrdenVenta model = null;
                if (string.IsNullOrEmpty(id))
                {
                    ViewBag.Title = "Nueva Orden de Venta";
                    model = new OrdenVenta() { FechaCreacion = DateTime.Now };
                }
                else
                {
                    ViewBag.Title = "Editar Orden de Venta";
                    model = ordenVentaRepositorio.GetOne(id);
                }
                return View(model);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [FiltroSeguridad]
        [HttpPost]
        public ActionResult Editar(OrdenVenta model)
        {
            try
            {
                ValidEntity(model);
                if (ModelState.IsValid)
                {
                    bool agregar = string.IsNullOrEmpty(model.Codigo);
                    if (agregar)
                    {
                        model.Estado = EstadoOrdenVenta.Emitido;
                        model.EmpleadoCreacionId = ((UserInformation)Session["user"]).UserId;
                        model.FechaCreacion = DateTime.Now;
                    }

                    model.Total = model.Detalles.Sum(x => x.Cantidad * x.Precio);

                    ordenVentaRepositorio.Save(model);
                    return Json(new { mensaje = agregar ? "La venta fue registrada." : "La venta fue actualizada." });
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Error");
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        public ActionResult Anular(string id)
        {
            try
            {
                OrdenVenta entity = ordenVentaRepositorio.GetOne(x => x.Codigo.Equals(id));
                if (Session["user"] != null)
                {

                    if (entity != null)
                    {
                        entity.EmpleadoAnulacionId = ((UserInformation)Session["user"]).UserId;
                        entity.FechaAnulacion = DateTime.Now;
                        entity.Estado = EstadoOrdenVenta.Anulado;
                        ordenVentaRepositorio.Anular(entity);
                        return Json(new { mensaje = "La venta fue anulada." });
                    }
                    else throw new Exception("La orden no existe.");
                }
                else throw new Exception("Porfavor ingrese al sistema.");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        public ActionResult Ver(string id)
        {
            try
            {
                OrdenVenta model = ordenVentaRepositorio.GetOne(id);
                ViewBag.Title = "Orden de venta: " + id;
                if (model == null) throw new Exception("El codigo no esta registrado.");
                return PartialView("_Ver", model);
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }
        public ActionResult GetAllLikePagin(OrdenVentaFiltro filter, int pageSize, int pageIndex)
        {
            try
            {
                int totalRows = 0;
                List<OrdenVenta> lista = ordenVentaRepositorio.GetAllLikePagin(filter, pageSize, pageIndex, ref totalRows);
                return Content(JsonConvert.SerializeObject(new
                {
                    lista = lista.Select(x => new
                    {
                        x.Codigo,
                        Nombre = x.EmpleadoCreacionNombreCompleto,
                        FechaCreacion = x.FechaCreacion.ToString("dd/MM/yyyy HH:mm"),
                        Total = x.Total.ToString("############0.00"),
                        x.Estado
                    }),
                    totalRows
                }));
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("_Error");
            }
        }

        #region Metodos

        public void ValidEntity(OrdenVenta item)
        {
            ModelState.Clear();
            if (item.Detalles == null || item.Detalles.Count == 0) ModelState.AddModelError("Detalles", "No puede registrar una venta vacia.");
            else if (item.Detalles.Any(x => x.Cantidad <= 0)) ModelState.AddModelError("Detalles", "Un item tiene como cantidad 0.");
        }

        #endregion
    }
}

Application/Cibercentro.WebApp/Views/OrdenVenta/Editar.cshtml
@model Cibercentro.Entidades.OrdenVenta

<link href="~/Content/pluggins/sweetalert/css/sweetalert.css" rel="stylesheet" />
<link href="~/Content/pluggins/select2/css/select2.min.css" rel="stylesheet" />
<link href="~/Content/pluggins/select2/css/select2.bootstrap4.css" rel="stylesheet" />
<link href="~/Content/pluggins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />


<div class="row">
    @using (Html.BeginForm("Editar", "OrdenVenta", FormMethod.Post, new { @id = "form-editar", @class = "col-md-12" }))
    {
        <h3>@ViewData["Title"]</h3>
        <hr />

        <div class="form-row">
            <div class="col-sm-12 col-md-12 text-right">
                <button type="button" class="btn btn-sm btn-primary" id="btnGuardar"><i class="fa fa-save"></i> Grabar</button>
                <a href="/OrdenVenta/Index" class="btn btn-sm btn-secondary"><i class="fa fa-chevron-left"></i> Regresar</a>
            </div>
        </div>
        <hr />
        <div id="mensaje"></div>
        @Html.HiddenFor(m => m.Codigo)
        <div class="form-group row">
            <label for="Codigo" class="col-sm-2 col-md-2 col-form-label text-truncate">Codigo: </label>
            <div class="col-sm-4 col-md-4">
                @Html.TextBox("Codigo_R", Model.Codigo, new { @class = "form-control form-control-sm", @readonly = "readonly" })
            </div>
            <label for="Fecha" class="col-sm-2 col-md-2 col-form-label text-truncate">Fecha: </label>
            <div class="col-sm-4 col-md-4">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-calendar"></i></span>
                    </div>
                    @Html.TextBoxFor(m => m.FechaCreacion, Model.FechaCreacion.ToString("dd/MM/yyyy"), new { @class = "form-control form-control-sm", @readonly = "readonly" })
                </div>
            </div>
        </div>
        <hr />
        <div class="form-group row">
            <div class="col-sm-6 col-md-6">
                <div class="input-group">
                    <input type="text" class="form-control form-control-sm" placeholder="Ingrese codigo de barras" id="FiltroCodigo" autofocus="" autocomplete="off" />
                    <div class="input-group-append">
                        <button class="btn btn-sm btn-outline-secondary" type="button" id="btnBuscarCodigo"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6">
                <select class="form-control form-control-sm" id="FiltroNombre"></select>
            </div>
        </div>
        <hr />
        <div class="table-responsive">
            <table class="table table-condensed table-hover" id="tblDetalle">
                <thead>
                    <tr class="thead-dark">
                        <th>Producto</th>
                        <th width="150">Cantidad</th>
                        <th width="150">Stock</th>
                        <th width="150">Precio</th>
                        <th width="150">SubTotal</th>
                        <th width="20"></th>
                    </tr>
                </thead>
                <tbody></tbody>
                <tfoot>
                    <tr class="thead-light">
                        <th colspan="4" class="text-bold text-right">Total</th>
                        <th>S/ <span class="total pull-right">0.00</span></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    }
</div>
<script src="~/Content/pluggins/sweetalert/js/sweetalert.min.js"></script>
<script src="~/Content/pluggins/select2/js/select2.min.js"></script>
<script src="~/Content/pluggins/select2/js/i18n/es.js"></script>
<script src="~/Content/pluggins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="~/Content/pluggins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>
<script>

    var listaProductos = null;
    $(function () {
        $("#FiltroCodigo").keypress(function (e) {
            var key = e.keyCode || event.keyCode;
            if (key === 13) $("#btnBuscarCodigo").click();
        });

        $("#btnBuscarCodigo").click(function (e) {
            var codigo = $("#FiltroCodigo").val();
            if (codigo != null && codigo.trim().length > 0) {
                var producto = listaProductos.find(function (r) { return r.Codigo === codigo; });
                if (producto) {
                    var trproducto = $('#tblDetalle tr[data-id="' + producto.ProductoId + '"]');
                    var i = $("#tblDetalle tbody tr").length;
                    if (trproducto.length > 0) {
                        var input = trproducto.find('input[type="number"]');
                        input.val((input.val() * 1) + 1);
                    } else {
                        var table = $('#tblDetalle tbody'),
                            tr = $('<tr>', { 'data-id': producto.ProductoId });
                        
                        tr.append($('<td>', { text: producto.Nombre }).append('<input type="hidden" name="Detalles[' + i + '].ProductoId" value="' + producto.ProductoId + '" />'));
                        tr.append($('<td>').append($('<input>', { type: 'number', min: '1', value: '1', step: '1', class: 'form-control form-control-sm text-right', name: 'Detalles[' + i + '].Cantidad' })));
                        tr.append($('<td>', { text: producto.Stock, class: "text-right" }));
                        tr.append($('<td>', { text: helper.format.decimal(producto.Precio), class: 'text-right precio' }).append('<input type="hidden" name="Detalles[' + i + '].Precio" value="' + producto.Precio + '" />'));
                        tr.append($('<td>', { text: helper.format.decimal(producto.Precio), class: 'text-right subtotal' }).append('<input type="hidden" name="Detalles[' + i + '].CodigoOrdenVenta" value="' + $('#Codigo').val() + '" />'));
                        tr.append($('<td>', { class: 'text-center' }).append('<a href="javascript:Eliminar(' + i + ')" style="font-size: 20px;"><i class="fa fa-trash text-danger"></i></a>'));

                        table.append(tr);
                    }
                    ActualizarTabla();
                }
                $("#FiltroCodigo").val(null);
            }
            e.preventDefault();
        });
        $('#form-editar').submit(e => { e.preventDefault(); });
        
        $('#btnGuardar').click(function (e) {
            swal({
                title: "Estas seguro?", text: "Los datos seran grabados", type: "warning",
                confirmButtonColor: "#f2b701", confirmButtonText: "Si", cancelButtonText: "No",
                showCancelButton: true, closeOnConfirm: false, showLoaderOnConfirm: true
            }, function (isConfirm) {
                if (isConfirm) {
                    var model = $("#form-editar").serialize();
                    $.ajax({
                        type: "POST",
                        url: "/OrdenVenta/Editar",
                        data: model,
                        dataType: 'json',
                        beforeSend: function () {
                            $('#form-editar button').attr("disabled", "disabled");
                            $("#mensaje").hide();
                            helper.wait.append('#mensaje');
                        },
                        complete: function () {
                            $('#form-modal-editar button').removeAttr("disabled");
                            helper.wait.remove('#mensaje');
                        },
                        success: function (result) {
                            swal({ title: "Alerta!", text: result.mensaje, type: "success" }, function () {
                                location.href = "/OrdenVenta/Index";
                            });
                        },
                        error: function (result) {
                            swal.close();
                            helper.wait.remove('#mensaje');
                            helper.error.show('#mensaje', result.responseText);
                            $('#form-editar button').removeAttr("disabled");
                        }
                    });
                }
            });
            e.preventDefault();
        });

        var wto;
        $('#tblDetalle').delegate('input[name$="].Cantidad"]', 'change', function () {
            clearTimeout(wto);
            wto = setTimeout(function () {
                ActualizarTabla();
            }, 500);
        });
        ListarProductos();
        $('#FiltroNombre').select2({
            placeholder: 'Seleccione un producto',
            allowClear: true,
            data: listaProductos.map(function (x) { return { id: x.ProductoId, text: x.Nombre, }; })
        }).on('select2:select', function (e) {
            var id = $(this).val();
            var producto = listaProductos.find(function (r) { return r.ProductoId == id; });
            var i = $("#tblDetalle tbody tr").length;
            var trproducto = $('#tblDetalle tr[data-id="' + id + '"]');
            if (trproducto.length > 0) {
                var input = trproducto.find('input[type="number"]');
                input.val((input.val() * 1) + 1);
            } else {
                var table = $('#tblDetalle tbody'),
                    tr = $('<tr>', { 'data-id': producto.ProductoId });
                tr.append($('<td>', { text: producto.Nombre }).append('<input type="hidden" name="Detalles[' + i + '].ProductoId" value="' + producto.ProductoId + '" />'));
                tr.append($('<td>').append($('<input>', { type: 'number', min: '1', value: '1', step: '1', class: 'form-control form-control-sm text-right', name: 'Detalles[' + i + '].Cantidad' })));
                tr.append($('<td>', { text: producto.Stock, class: "text-right" }));
                tr.append($('<td>', { text: helper.format.decimal(producto.Precio), class: 'text-right precio' }).append('<input type="hidden" name="Detalles[' + i + '].Precio" value="' + producto.Precio + '" />'));
                tr.append($('<td>', { text: helper.format.decimal(producto.Precio), class: 'text-right subtotal' }).append('<input type="hidden" name="Detalles[' + i + '].CodigoOrdenVenta" value="' + $('#Codigo').val() + '" />'));
                tr.append($('<td>', { class: 'text-center' }).append('<a href="javascript:Eliminar(' + i + ')" style="font-size: 20px;"><i class="fa fa-trash text-danger"></i></a>'));
                table.append(tr);
            }
            ActualizarTabla();
        });

    });

    function ListarProductos() {
        $.ajax({
            type: "GET",
            url: '/Producto/GetAll',
            dataType: 'json',
            async: false,
            success: function (data) {
                listaProductos = data;
            }
        });
    }

    function ActualizarTabla() {
        var total = 0;
        $.each($('#tblDetalle tbody tr'), function (i, tr) {
            $(tr).find('input[name$="].CodigoOrdenVenta"]').attr('name', 'Detalles[' + i + '].CodigoOrdenVenta');
            $(tr).find('input[name$="].ProductoId"]').attr('name', 'Detalles[' + i + '].ProductoId');
            $(tr).find('input[name$="].Precio"]').attr('name', 'Detalles[' + i + '].Precio');
            $(tr).find('input[name$="].Cantidad"]').attr('name', 'Detalles[' + i + '].Cantidad');
            $(tr).find('a').attr('href', 'javascript:Eliminar(' + i + ')');
            
            var precio = $(tr).find('td.precio').text();
            var cantidad = $(tr).find('input[type="number"]').val();
            $(tr).find('td.subtotal').text(helper.format.decimal(precio * cantidad));
            total += precio * cantidad;
        })
        $('#tblDetalle tfoot span.total').text(helper.format.decimal(total));
    }

    function Eliminar(i) {
        $($('#tblDetalle tbody tr')[i]).remove();
        ActualizarTabla();
    }
</script>

Application/Cibercentro.WebApp/Views/OrdenVenta/Index.cshtml
@{
    ViewBag.Title = "Orden Venta";
}
<link href="~/Content/pluggins/sweetalert/css/sweetalert.css" rel="stylesheet" />
<link href="~/Content/pluggins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-12">
        <h3>Lista de ventas</h3>
        <hr />
        <div class="form-row">
            <div class="col-sm-3 col-md-3 mb-2">
                <input type="text" class="form-control form-control-sm" placeholder="Codigo" id="FCodigo" />
            </div>
            <div class="col-sm-5 col-md-5 mb-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control form-control-sm" placeholder="Encargado" id="FEmpleado" />
                </div>
            </div>
            <div class="col-sm-4 col-md-4 mb-2">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                    </div>
                    <input class="form-control form-control-sm datepicker" placeholder="Fecha" id="FFecha" autocomplete="off" disabled="disabled" />
                </div>
            </div>
            <div class="col-sm-12 col-md-12 text-right">
                <button id="btnBuscar" type="button" class="btn btn-sm btn-secondary"><i class="fa fa-search"></i> Buscar</button>
                <a href="/OrdenVenta/Editar" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Nuevo</a>
            </div>
        </div>
        <div id="mensaje"></div>
        <hr />
        <div class="table-responsive">
            <table id="tblIndex"
                   class="table table-bordered table-hover table-nowrap"
                   data-pagesize="@Cibercentro.WebApp.Common.SettingsManager.PageSize"
                   data-pageindex="1"
                   data-totalrows="0"
                   data-function="ordenventa_index.Listar"
                   data-paginator="paginator">
                <thead>
                    <tr class="thead-dark">
                        <th width="40"></th>
                        <th width="20">Nº</th>
                        <th width="150">Correlativo</th>
                        <th>Creador</th>
                        <th width="150">Fecha</th>
                        <th width="150">Total</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
        <div class="form-row">
            <div class="col-md-12 text-right" id="paginator"></div>
        </div>
    </div>
</div>

<div class="modal" id="modal" role="dialog">
    <div id="ventana-editar"></div>
</div>

<script src="~/Content/pluggins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="~/Content/pluggins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>
<script src="~/Content/pluggins/sweetalert/js/sweetalert.min.js"></script>
<script>

    var ordenventa_index = {
        Listar: function (page) {
            var table = $("#tblIndex");
            var model = {
                'filter.Codigo': $("#FCodigo").val(),
                'filter.Empleado': $("#FEmpleado").val(),
                'pageIndex': page,
                'pageSize': table.data('pagesize')
            };
            $.ajax({
                url: "/OrdenVenta/GetAllLikePagin",
                type: "GET",
                data: model,
                dataType: "json",
                success: function (data) {
                    table.data('pageindex', page);
                    table.data('totalrows', data.totalRows);
                    ordenventa_index.GenerarTabla(table, data.lista);
                    if (data.totalRows === 0) table.children('tbody').append("<tr><td colspan='6' class='text-center text-bold'>No existen registros</td></td>");
                },
                error: function (data) {
                    helper.error.show('msgIndex', data.responseText);
                }
            });
        },
        GenerarTabla: function (table, lista) {
            var tbody = table.children('tbody');
            tbody.children('tr').remove();
            var rows = '';
            var numero = (table.data('pagesize') * table.data('pageindex')) - table.data('pagesize');
            $.each(lista, function (i, r) {
                rows += helper.string.format('<tr class="{0}">', r.Estado == 2 ? "table-danger" : "");
                rows += '<td class="text-center"><ul class="list-inline">';
                if (r.Estado == 1) {
                    rows += helper.string.format('<li class="list-inline-item"><a href="javascript:ordenventa_index.Anular(\'{0}\')" title="Anular"><i class="fa fa-trash text-danger"></i></a></li>', r.Codigo);
                }
                rows += helper.string.format('<li class="list-inline-item"><a href="javascript:ordenventa_index.Ver(\'{0}\')" title="Ver"><i class="fa fa-eye text-primary"></i></a></li>', r.Codigo);
                rows += '</ul></td>';
                rows += helper.string.format('<td class="text-right">{0}</td>', ++numero);
                rows += $('<td>', { text: r.Codigo, class: "text-center" }).prop('outerHTML');
                rows += $('<td>', { text: r.Nombre }).prop('outerHTML');
                rows += $('<td>', { text: r.FechaCreacion, class: "text-center" }).prop('outerHTML');
                rows += $('<td>', { text: r.Total, class: "text-right" }).prop('outerHTML');
                rows += '</tr>';
            });
            helper.pagination.update(table);
            tbody.append(rows);
        },
        Anular: function (codigo) {
            swal({
                title: "¿Esta seguro de anular la venta?", type: "warning",
                confirmButtonColor: "#f2b701", confirmButtonText: "Si", cancelButtonText: "No",
                showCancelButton: true, closeOnConfirm: false, showLoaderOnConfirm: true
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: "POST",
                        url: "/OrdenVenta/Anular",
                        data: { id: codigo },
                        dataType: 'json',
                        beforeSend: function () {
                            $('#form-editar button').attr("disabled", "disabled");
                            $("#mensaje").hide();
                            helper.wait.append('#mensaje');
                        },
                        complete: function () {
                            $('#form-modal-editar button').removeAttr("disabled");
                            helper.wait.remove('#mensaje');
                        },
                        success: function (result) {
                            swal({ title: "Alerta!", text: result.mensaje, type: "success" }, function () {
                                ordenventa_index.Listar($('#tblIndex').data('pageindex'));
                            });
                        },
                        error: function (result) {
                            swal.close();
                            helper.wait.remove('#mensaje');
                            helper.error.show('#mensaje', result.responseText);
                            $('#form-editar button').removeAttr("disabled");
                        }
                    });
                }
            });
        },
        Ver: function (codigo) {
            $.ajax({
                type: "GET",
                url: '/OrdenVenta/Ver',
                data: { id: codigo },
                cache: false,
                beforeSend: function () {
                    helper.wait.modal('ventana-editar');
                    $('#modal').modal('show');
                },
                success: function (data) {
                    $('#ventana-editar').html(data);
                },
                error: function (result) {
                    $('#modal').modal('hide');
                    helper.error.show('#mensaje', result.responseText);
                }
            });
        }
    };
    $(function () {
        $('.datepicker').datepicker({
            language: 'es',
            orientation: 'bottom',
            'autoclose': true,
            format: 'dd/mm/yyyy'
        });
        $('input[type="text"]').keypress(function (e) {
            var key = e.keyCode || event.keyCode;
            if (key == 13) ordenventa_index.Listar(1);
        });
        ordenventa_index.Listar(1);
    });
</script>

Application/Cibercentro.WebApp/Views/OrdenVenta/_Ver.cshtml
@model Cibercentro.Entidades.OrdenVenta
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header with-border">
            <h4 class="modal-title">@ViewBag.Title</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="table-responsive">
                    <table class="table table-condensed table-bordered table-sm">
                        <thead>
                            <tr class="table-primary">
                                <th width="20">#</th>
                                <th>Nombre</th>
                                <th width="150">Cantidad</th>
                                <th width="150">Precio</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                                foreach (var detalle in Model.Detalles)
                                {
                                    <tr>
                                        <td>@(i++)</td>
                                        <td>@detalle.Producto.Nombre</td>
                                        <td class="text-right">@detalle.Cantidad</td>
                                        <td>S/ <span class="pull-right">@detalle.Precio</span></td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal"><i class="fa fa-chevron-left"></i> Regresar</button>
        </div>
    </div>
</div>